name: Ensure pull requests to main are from dev

on:
  pull_request:
    branches:
      - main

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if pull request is from dev
        run: |
          if [[ ${{ github.event.pull_request.head.ref }} != 'dev' ]]; then
            echo "Pull requests to main must come from dev"
            exit 1
          fi
        shell: bash
